# Linear Algebra 1

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
A = np.array([[3,-2,-1],[6,-2,2],[-9,7,1]])
B = np.array([0,6,-1])

N = len(A)
x = np.zeros(N)

for j in range(N):
    for i in range(j+1, N):
        coef = A[i][j]/A[j][j]
        for k in range(N):
            A[i][k] -= coef * A[j][k]
        B[i] -= coef * B[j]

x[N-1] = B[N-1]/A[N-1][N-1]
for k in range(N-1, -1, -1):
    sum = np.dot(A[k][k+1:],x[k+1:])
    x[k] = (B[k] - sum)/A[k][k]

print(A)
print(x)

[[ 3 -2 -1]
 [ 0  2  4]
 [ 0  0 -4]]
[1. 1. 1.]


In [6]:
A = np.array([[2,1,-1,2],[4,5,-3,6],[-2,5,-2,6],[4,11,-4,8]])
B = np.array([5,9,4,2])

N = len(A)
x = np.zeros(N)

for j in range(N):
    for i in range(j+1, N):
        coef = A[i][j]/A[j][j]
        for k in range(N):
            A[i][k] -= coef * A[j][k]
        B[i] -= coef * B[j]

x[N-1] = B[N-1]/A[N-1][N-1]
for k in range(N-1, -1, -1):
    sum = np.dot(A[k][k+1:],x[k+1:])
    x[k] = (B[k] - sum)/A[k][k]

print(A)
print(x)

[[ 2  1 -1  2]
 [ 0  3 -1  2]
 [ 0  0 -1  4]
 [ 0  0  0  2]]
[ 1. -2.  1.  3.]


In [7]:
from scipy import linalg

A = np.array([[3,-2,-1],[6,-2,2],[-9,7,1]])

A.T
D = linalg.inv(A)
A.dot(D)
linalg.det(A)
la,v = linalg.eig(A)
print (la)
print (v[:,0], v[:,1], v[:,2])

B = np.array([0,6,-1])
np.linalg.solve(A,B)
A.dot(np.linalg.solve(A,B)) - B

[-3.82445836+0.j  1.42707587+0.j  4.39738249+0.j]
[ 0.06919005  0.62490619 -0.7776278 ] [ 0.54978724  0.67701889 -0.48926416] [-0.44061233 -0.135829    0.88736196]


array([ 6.66133815e-16,  1.77635684e-15, -2.22044605e-16])

In [25]:
A = np.array([[2,1,-1,2],[4,5,-3,6],[-2,5,-2,6],[4,11,-4,8]])
B = np.array([5,9,4,2])

C = np.linalg.solve(A,B)
D = linalg.inv(A)
C, D

(array([ 1., -2.,  1.,  3.]),
 array([[ 2.16666667e+00, -1.16666667e+00, -8.32667268e-17,
          3.33333333e-01],
        [ 6.66666667e-01, -6.66666667e-01, -2.22044605e-16,
          3.33333333e-01],
        [ 1.30000000e+01, -8.00000000e+00,  1.00000000e+00,
          2.00000000e+00],
        [ 4.50000000e+00, -2.50000000e+00,  5.00000000e-01,
          5.00000000e-01]]))

In [27]:
A.dot(D)

array([[ 1.00000000e+00, -1.77635684e-15,  1.11022302e-16,
         5.55111512e-16],
       [ 3.55271368e-15,  1.00000000e+00,  3.33066907e-16,
         1.33226763e-15],
       [ 0.00000000e+00, -1.77635684e-15,  1.00000000e+00,
         4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00, -4.44089210e-16,
         1.00000000e+00]])

In [30]:
A = np.array([[2,1,-1,2],[4,5,-3,6],[-2,5,-2,6],[4,11,-4,8]])
B = np.array([5,9,4,2])

P, L, U = linalg.lu(A)
P, L, U

LU = linalg.lu_factor(A)
x = linalg.lu_solve(LU, B)
x

array([ 1., -2.,  1.,  3.])