In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
def golden3D(x,dr,TOL):
    R, err, loop = 0.61803399,10.,-1
    adr = np.sqrt(dr[0]**2 + dr[1]**2 + dr[2]**2)
    a = x - (dr / adr)
    b = x + (dr / adr)
    while (err > TOL):
        loop = loop + 1
        x1 = b - R * (b - a)
        x2 = a + R*(b - a)
        f1 = f(x1)
        f2 = f(x2)
        if(f2>f1): 
            b = x2
        else: 
            a = x1
        err = sum((a - b)**2)
        err = np.sqrt(err)
    xmin=a
    return xmin,err,loop

In [5]:
def f(x):
    return 100 * (x[1] - x[0]**2)**2 + (1 - x[0])**2 + 100 * (x[2] - x[1]**2)**2 + (1 - x[2])**2

In [6]:
def gradf(x):
    return np.array([(-400) * x[0] * (x[1] - x[0]**2) - 2 * (1 - x[0]), 200 * (x[1] - x[0]**2) - 400 * x[1] * (x[2] - x[1]**2), 200 * (x[2] - x[1]**2) - 2 * (1 - x[2])])

In [12]:
TOL = 10**(-5)
x = np.array([0,2,1])
dr1 = gradf(x)
x1, err, loop = golden3D(x, dr1, TOL)
err=(x1[2] - x[2])**2 + (x1[1] - x[1])**2 + (x1[0] - x[0])**2


cnt= 0
while (err>TOL):
    cnt = cnt + 1
    dr2 = gradf(x) + ((gradf(x)[0]**2 + gradf(x)[1]**2 + gradf(x)[2]**2) / (dr1[0]**2 + dr1[1]**2 + dr1[2]**2)) * dr1
    x1, err, loop = golden3D(x, dr2, TOL)
    dr1 = dr2
    err = (x1[2] - x[2])**2 + (x1[1] - x[1])**2 + (x1[0] - x[0])**2
    print(x1)
    x = x1
print('minimum point : ({},{},{})'.format(x[0],x[1],x[2]),'\n','%d iterations'%cnt)

[6.98430125e-04 1.02219782e+00 1.20952904e+00]
[0.00524708 0.74266301 1.14464261]
[0.0376606  0.28621915 0.255481  ]
[ 0.07632521  0.0316825  -0.01597205]
[0.08967961 0.00210276 0.00691822]
[0.12905453 0.01959017 0.02701683]
[0.30571686 0.07010761 0.01756375]
[0.31559387 0.10201514 0.01359899]
[0.33576521 0.10580894 0.02687805]
[0.45193482 0.22034992 0.03519356]
[0.51281914 0.24772939 0.05642457]
[0.50715369 0.26170947 0.0714349 ]
[0.51434227 0.2626788  0.08118008]
[0.56571583 0.3294505  0.09784818]
[0.62196953 0.36985206 0.12960801]
[0.61386926 0.38138506 0.14349088]
[0.61762608 0.38072828 0.15398735]
[0.63924629 0.41883413 0.16940235]
[0.70252276 0.47771333 0.2174197 ]
[0.69288657 0.48542273 0.23375222]
[0.69566723 0.48372807 0.24100145]
[0.71810989 0.52086694 0.26119201]
[0.76252704 0.56416207 0.30878361]
[0.7529276  0.57075383 0.32091947]
[0.75413298 0.56844191 0.32826307]
[0.76451239 0.59201776 0.34437906]
[0.81911607 0.65542023 0.41751881]
[0.80890965 0.6585185  0.43110575]
[0.81